SimplesDespesas/Controllers/MovimentoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Modelos;

namespace SimplesDespesas.Controllers
{ 
    public class MovimentoController : Controller
    {
        private DataContext db = new DataContext();

        //
        // GET: /Movimento/

        public ViewResult Index()
        {
            return View(db.Movimentos.ToList());
        }

        //
        // GET: /Movimento/Details/5

        public ViewResult Details(int id)
        {
            Movimento movimento = db.Movimentos.Find(id);
            return View(movimento);
        }

        //
        // GET: /Movimento/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Movimento/Create

        [HttpPost]
        public ActionResult Create(Movimento movimento)
        {
            if (ModelState.IsValid)
            {
                db.Movimentos.Add(movimento);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(movimento);
        }
        
        //
        // GET: /Movimento/Edit/5
 
        public ActionResult Edit(int id)
        {
            Movimento movimento = db.Movimentos.Find(id);
            return View(movimento);
        }

        //
        // POST: /Movimento/Edit/5

        [HttpPost]
        public ActionResult Edit(Movimento movimento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movimento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movimento);
        }

        //
        // GET: /Movimento/Delete/5
 
        public ActionResult Delete(int id)
        {
            Movimento movimento = db.Movimentos.Find(id);
            return View(movimento);
        }

        //
        // POST: /Movimento/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Movimento movimento = db.Movimentos.Find(id);
            db.Movimentos.Remove(movimento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SimplesDespesas/Controllers/PlanoDeContaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Modelos;
using Repositorio.Interfaces;

namespace SimplesDespesas.Controllers
{ 
    public class PlanoDeContaController : AplicationController
    {

        PlanoDeContasRepositorio repoPalnoDeContas = new PlanoDeContasRepositorio();
       
        public ViewResult Index()
        {

            return View(repoPalnoDeContas.List(UsuarioSessao().Id));
        }

        public ViewResult Details(int id)
        {
            ViewBag.TipoPlano = new SelectList(new[] { new { Value=((int)TipoPlano.Despesas).ToString(), Text=TipoPlano.Despesas.ToString(), Selected=true },
                                                        new { Value=((int)TipoPlano.Receitas).ToString(), Text=TipoPlano.Receitas.ToString(), Selected=false } },
                                                "Value", "Text", "Selected");

            PlanoDeConta planodeconta = repoPalnoDeContas.Detalhes(id, UsuarioSessao().Id);
            return View(planodeconta);
        }

         public ActionResult Create()
        {
            ViewBag.TipoPlano = new SelectList(new[] { new { Value=((int)TipoPlano.Despesas).ToString(), Text=TipoPlano.Despesas.ToString(), Selected=true },
                                                        new { Value=((int)TipoPlano.Receitas).ToString(), Text=TipoPlano.Receitas.ToString(), Selected=false } },
                                                "Value", "Text", "Selected");

            return View();
        } 

     
        [HttpPost]
        public ActionResult Create(PlanoDeConta planodeconta)
        {
            if (ModelState.IsValid)
            {
                repoPalnoDeContas.Incluir(planodeconta,UsuarioSessao());
                
                return RedirectToAction("Index");  
            }

            return View(planodeconta);
        }
        
     
        public ActionResult Edit(int id)
        {
            ViewBag.TipoPlano = new SelectList(new[] { new { Value=((int)TipoPlano.Despesas).ToString(), Text=TipoPlano.Despesas.ToString(), Selected=true },
                                                        new { Value=((int)TipoPlano.Receitas).ToString(), Text=TipoPlano.Receitas.ToString(), Selected=false } },
                                                "Value", "Text", "Selected");

            PlanoDeConta planodeconta = repoPalnoDeContas.Detalhes(id, UsuarioSessao().Id);
            return View(planodeconta);
        }

       
        [HttpPost]
        public ActionResult Edit(PlanoDeConta planodeconta)
        {
            if (ModelState.IsValid)
            {
                repoPalnoDeContas.alterar(planodeconta.Id, planodeconta, UsuarioSessao().Id);
                return RedirectToAction("Index");
            }
            return View(planodeconta);
        }

      
 
        public ActionResult Delete(int id)
        {
            PlanoDeConta planodeconta = repoPalnoDeContas.Detalhes(id, UsuarioSessao().Id);
            return View(planodeconta);
        }

       

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            repoPalnoDeContas.Excluir(id, UsuarioSessao().Id); 
            return RedirectToAction("Index");
        }

    }
}

SimplesDespesas/Controllers/TipoPagamentoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Modelos;

namespace SimplesDespesas.Controllers
{ 
    public class TipoPagamentoController : Controller
    {
        private DataContext db = new DataContext();

        //
        // GET: /TipoPagamento/

        public ViewResult Index()
        {
            return View(db.TipoPagamentos.ToList());
        }

        //
        // GET: /TipoPagamento/Details/5

        public ViewResult Details(int id)
        {
            TipoPagamento tipopagamento = db.TipoPagamentos.Find(id);
            return View(tipopagamento);
        }

        //
        // GET: /TipoPagamento/Create

        public ActionResult Create()
        {
            ViewBag.TipoConta = new SelectList(new[] { new { Value=((int)TipoConta.Avista).ToString(), Text=TipoConta.Avista.ToString(), Selected=true },
                                                        new { Value=((int)TipoConta.Cartao).ToString(), Text=TipoConta.Cartao.ToString(), Selected=false } },
                                                "Value", "Text", "Selected");

            
            return View();
        } 

        //
        // POST: /TipoPagamento/Create

        [HttpPost]
        public ActionResult Create(TipoPagamento tipopagamento)
        {
            if (ModelState.IsValid)
            {
                db.TipoPagamentos.Add(tipopagamento);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(tipopagamento);
        }
        
        //
        // GET: /TipoPagamento/Edit/5
 
        public ActionResult Edit(int id)
        {
            TipoPagamento tipopagamento = db.TipoPagamentos.Find(id);
            return View(tipopagamento);
        }

        //
        // POST: /TipoPagamento/Edit/5

        [HttpPost]
        public ActionResult Edit(TipoPagamento tipopagamento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipopagamento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipopagamento);
        }

        //
        // GET: /TipoPagamento/Delete/5
 
        public ActionResult Delete(int id)
        {
            TipoPagamento tipopagamento = db.TipoPagamentos.Find(id);
            return View(tipopagamento);
        }

        //
        // POST: /TipoPagamento/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            TipoPagamento tipopagamento = db.TipoPagamentos.Find(id);
            db.TipoPagamentos.Remove(tipopagamento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SimplesDespesas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title>Simples Despesas</title>
  <link href="@Url.Content("~/content/styles/layout.css")" rel="stylesheet" type="text/css" />
  <link href="@Url.Content("~/content/styles/mediaqueries.css")" rel="stylesheet" type="text/css" /> 
  <script src="@Url.Content("~/scripts/jquery-mobilemenu.min.js")" type="text/javascript"></script>
  <script src="@Url.Content("~/scripts/jquery-1.7.2.min.js")" type="text/javascript"></script>
 
<script>
    $(document).ready(function () {
        $('.topnav').mobileMenu({
            combine: false,
            switchWidth: 600,
            prependTo: 'nav#topnav'
        });
    });
</script>
</head>
<body>

<div class="wrapper row1">
  <header id="header">
    <hgroup>
      <h1><a href=#><span>S</span>imples <span>D</span>espesas</a></h1>
      <h2>Controle Pessoal de Gastos</h2>
    </hgroup>
    <!-- ################################################################################################ -->
    <nav id="topnav">
      <ul class="topnav clear">
       
       @if (!Request.IsAuthenticated)
       { 
         <li> @Html.ActionLink("Entrar", "LogOn", "Account")</li>
         <li> @Html.ActionLink("Cadastre-se", "Register", "Account")</li>
       }
       
       @if (Request.IsAuthenticated)
       {     
        <li>@Html.ActionLink("Home", "Dashboard", "Home")</li>
        <li>@Html.ActionLink("Plano de Contas", "Index", "PlanoDeConta")</li>
        <li>@Html.ActionLink("Tipos de Pagamentos", "Index", "TipoPagamento")</li>
        <li>@Html.ActionLink("Lançar Despesas", "Index", "Movimento")</li>
        <li>@Html.ActionLink("Sair", "LogOff", "Account")</li>           
       } 
      </ul>
    </nav>
    <div class="clear"></div>
  </header>
</div>

    <div class="container">
        @RenderBody()

        <hr />
        <footer>
            <p>
                © Desenvolvido por <a href="#" title="Site" target="_blank">Bruno Borges.</a></p>
            <p>
            <small>Versão Beta</small>
        </footer>
    </div>

    @RenderSection("javascriptFimHtml", required: false)
</body>
</html>

SimplesDespesas/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}